# fly.toml app configuration file generated for xsd-viewer on 2024-12-02T15:12:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xsd-viewer'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
